server:
  port: 8766

spring:
  application:
    name: zuul-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
---
spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    client-service:
      path: /client/**
      service-id: client2-service
#      service-id: client-service



#  ignored-services: "*"