spring:
  application:
    name: client2-service
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

metal-service:
  url: http://localhost:8081

metal-service-updater:
   url: http://localhost:8070/
